cloud:
  aws:
    credentials:
      instanceProfile: true
      access-key: abc
      secret-key: abc
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: abcd
      cloud-front-url: abcd
      directory:
        path:
          foods: foods/
      mock:
        port: 10000

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error