language: java
jdk:
  - openjdk11

branches:
  only:
    - main
    - dev

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean :module-api:build

install: true