spring:
  profiles:
    active: local
    default: local
    include:
      - domain-dev
      - domain-local
      - external
      - oauth
      - aws-local
      - aws-dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
