server:
  port: 8000

jwt:
  token:
    secret:
      key: JWTSecretKey
    expiration:
      seconds: 60480000


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
