spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        default_batch_fetch_size: 500
    open-in-view: false
    show-sql: true
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      maximum-pool-size: 40
      max-lifetime: 60000
      jdbc-url: jdbc:mysql://localhost:3306/dev?serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 5000
      pool-name: Spring-HikariPool

userlock:
  datasource:
    hikari:
      maximum-pool-size: 20
      max-lifetime: 60000
      jdbc-url: jdbc:mysql://localhost:3306/dev?serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 5000
      pool-name: UserLock-HikariPool