name: shared-food-action

on:
  push:
    branches:
      - chore/#192
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

env:
  NOTIFICATION_RESOURCE_PATH: ./module-external/src/main/resources/application-notification.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set timezone to KST
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Notification Update Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.NOTIFICATION_RESOURCE_PATH }}
        env:
          slack.token: ${{ secrets.SLACK_NOTIFICATION }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew clean :module-api:build sonarqube

#      - name: Build with Gradle
#        run: ./gradlew clean :module-api:build
#        shell: bash

#      - name: Make code zip file
#        run: zip -r ./$GITHUB_SHA.zip .
#        shell: bash
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}
#
#      - name: Upload to S3
#        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://kkh-bucket/$GITHUB_SHA.zip
#
#      - name: Code Deploy
#        run: aws deploy create-deployment --application-name github-action-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name shared-food-github-action-group --s3-location bucket=kkh-bucket,bundleType=zip,key=$GITHUB_SHA.zip
